### ISSUE TITLE
Erreur à l'installation

### ISSUE THREAD

**Issue by GomezCeline** [YounitedCredit/younitedpay-module-magento2#6]
Bonjour, 
Je rencontre cette erreur sur un Magento 2.3.6 lors de la compilation :

`
Errors during compilation:
	YounitedCredit\YounitedPay\Block\Adminhtml\Form\Field\MaturitiesConfig
		Extra parameters passed to parent construct: $secureRenderer. File: /www/vendor/younitedcredit/younitedpay-module-magento2/Block/Adminhtml/Form/Field/MaturitiesConfig.php
Total Errors Count: 1
`

Cordialement

**Comment by kgleizes** [comment]
Bonjour, 

Ce point a pourtant été testé sur cette version de Magento2 et doit être lié à une configuration serveur.

Vous avez deux solutions, la première c'est de mettre à jour votre version de Magento et les dernières versions
ont bien ce troisième paramètre "$secureRenderer".

La seconde solution (immédiate) est de patcher le module et de remplacer ici : 
vendor/younitedcredit/younitedpay-module-magento2/Block/Adminhtml/Form/Field/MaturitiesConfig.php - L.55
Remplacer : 
`parent::__construct($context, $data, $secureRenderer);`

Par : 
`parent::__construct($context, $data);`

Et vous pourrez correctement terminer votre installation.

Sachant que c'est un cas isolé, je me permet de fermer cette anomalie.

Vous pouvez néanmoins l'ouvrir à nouveau si la résolution n'était pas correcte pour votre cas de figures.

En vous souhaitant une excellente journée.

**Comment by sebgar** [comment]
Bonjour 

J'ai exactement le même problème avec un Magento 2.3.6

la classe Magento\Backend\Block\Template herité n'a que deux paramétres "public function __construct(\Magento\Backend\Block\Template\Context $context, array $data = [])"

sur une version 2.4.3-P3
public function __construct(
        \Magento\Backend\Block\Template\Context $context,
        array $data = [],
        ?JsonHelper $jsonHelper = null,
        ?DirectoryHelper $directoryHelper = null
    ) {

Je passe par une installation composer donc je ne peux pas modifier le code

Avez vous une solution ?

**Comment by kgleizes** [comment]
Bonjour @sebgar, 

Pourriez-vous confirmer que le problème concerne bien la classe : 
YounitedCredit\YounitedPay\Block\Adminhtml\Form\Field\MaturitiesConfig

Si c'est bien le cas, cette classe étends celle-ci : 
\Magento\Config\Block\System\Config\Form\Field\FieldArray\AbstractFieldArray

Qui elle même étend : 
\Magento\Config\Block\System\Config\Form\Field

C'est cette dernière qui a trois paramètres à la construction:
![Image](https://github.com/user-attachments/assets/43bd622c-8031-450f-ac7d-8fb9426b1ca8)

Nous allons effectuer des tests sur les différentes versions vu que le troisième paramètre est optionnel pour 
ne pas le fournir ($secureRenderer) et vous fournir une solution définitive.

En attendant comme solution immédiate vous pouvez sur votre serveur cible appliquer le patch mentionné
précédemment: 

Dans le fichier : 
vendor/younitedcredit/younitedpay-module-magento2/Block/Adminhtml/Form/Field/MaturitiesConfig.php - L.55
Remplacer :
`parent::__construct($context, $data, $secureRenderer);
`
Par :
`parent::__construct($context, $data);`

Avec votre confirmation j'ouvrirai un ticket pour tester la mise à jour de la construction de la classe mentionnée
sur les versions de Magento2 testées actuellement (2.2, 2.3 et 2.4.x).

Merci.

**Comment by sebgar** [comment]
Bonjour 

Oui c'est bien cette classe, mais sur la version 2.3.6, 2.4.3 et 2.4.6, je ne trouve pas de champ "$secureRenderer"
La seule method "__construct" dans toute la chaine d'heritage c'est la classe "Magento\Backend\Block\Template"

Sur quelle version êtes vous ?

**Comment by kgleizes** [comment]
Bonjour,

Je viens de vérifier sur 2.4.4 et 2.4.6 à l'instant pour vous remonter la capture et les classes.

La classe MaturitiesConfig n'a pas pour parent direct "Magento\Backend\Block\Template" ce n'est donc pas cette
construction là qui devrait être effectuée lors de la compilation.

La classe "Field" si on remonte la construction hérite bien de "Magento\Backend\Block\Template" mais elle
construit bien son parent avec : 
`parent::__construct($context, $data);`

C'est natif de Magento2.

Quoi qu'il en soit nous allons tester la possibilité de construire "\Magento\Config\Block\System\Config\Form\Field\FieldArray\AbstractFieldArray" sans ce troisième paramètre
vu qu'il est optionnel nous devrions pouvoir fournir cette amélioration pour éviter de retomber sur cette curiosité de compilation.

Merci pour votre retour.
